### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by omrid594** [vaguileradiaz/tinfoleak#33]
Hey, does the program still working?

**Comment by pyttam** [comment]
I second this question. Awesome tool, but does not appear to work anymore.

**Comment by ghost** [comment]
try the Windows-Exe version, it works great with wine

**Comment by pyttam** [comment]
Ah yes, that worked. Thanks for the tip!

-------- Original Message --------

**Comment by ChristopherBoots** [comment]
> try the Windows-Exe version, it works great with wine

could you quickly walk me through how you run the Windows-Exe version with wine? 'wine tinfoleak.py invokes 'wine32 missing', but when attempt to install it's missing or obsolete, and libwine doesn't seem to do the trick.  i'm getting 'except exception, e:' syntax errors the standard way and am not familiar with wine. greatly appreciated

**Comment by ghost** [comment]
Yes of course

You're using wine with the wrong file. Here is what I did:

- `wget "https://github.com/vaguileradiaz/tinfoleak/raw/master/Windows-EXE/tinfoleak-EXE.zip"`
- `unzip tinfoleak-EXE.zip`
- `cd  tinfoleak-EXE`
- `wine tinfoleak.exe`

If you still encouter errors, you need to download the 32bit version of wine, make sure you do the following if you're using a debian based disto: `apt install wine32 wine64`

**Comment by pyttam** [comment]
Yes, this is what I did as well. Assuming you're on a Debian-based distro, I simply installed wine via `sudo apt install wine` , then downloaded the ZIP file from `https://github.com/vaguileradiaz/tinfoleak/raw/master/Windows-EXE/tinfoleak-EXE.zip`, and did exactly as @jJit0 described.  Here's a quick GIF in case it's at all helpful https://privatty.com/en/n/H3O6wpdL#WcCU07jvXL .

**Comment by ChristopherBoots** [comment]
> Yes of course
> 
> You're using wine with the wrong file. Here is what I did:
> 
>     * `wget "https://github.com/vaguileradiaz/tinfoleak/raw/master/Windows-EXE/tinfoleak-EXE.zip"`
> 
>     * `unzip tinfoleak-EXE.zip`
> 
>     * `cd  tinfoleak-EXE`
> 
>     * `wine tinfoleak.exe`
> 
> 
> If you still encouter errors, you need to download the 32bit version of wine, make sure you do the following if you're using a debian based disto: `apt install wine32 wine64`

Thanks, i appreciate the help. My Kali  machine went down Saturday but now I'm back up. So i followed those steps and used 'wine tinfoleak.exe' and i get a response 'it looks like wine32 is missing, you should install it.' I thought i had but okay, so i 'apt install wine32' and i get 'Package wine32 is not available, but is referred to by another package... the following packages replace it: libwine'. So i install libwine and no luck. I'll have to do some digging. There is a line at the bottom that says 'E: Package 'wine32' has no installation candidate'. Does that mean anything to you?

**Comment by ghost** [comment]
Ok, it’s probably because you didn’t add 32bit architecture into your sources. Do the following:

- `dpkg --add-architecture i386`
- `apt update`
- `apt install wine{32,64} mono-complete`

That should work

BTW, mono is useful to install, as it launch .Net-Framework binaries like windows portable apps.

**Comment by ChristopherBoots** [comment]
> Ok, it’s probably because you didn’t add 32bit architecture into your sources. Do the following:
> 
>     * `dpkg --add-architecture i386`
> 
>     * `apt update`
> 
>     * `apt install wine{32,64} mono-complete`
> 
> 
> That should work
> 
> BTW, mono is useful to install, as it launch .Net-Framework binaries like windows portable apps.

Ok, making progress - **thank you** -but new error:

```
$ wine tinfoleak.exe

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt4plugins.py", line 43, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 546, in >load_module

ImportError: DLL load failed: No access to memory location.
Failed to execute script pyi_rth_qt4plugins
```
Searching the forums i only find fixes for windows users with this error. Again i'll keep looking but you've been spot on thus far

**Comment by jJit0** [comment]
Ok, I can help you remotely, by sharing in realtime your terminal.

do the following:
- `apt update`
- `apt install tmate tmux -y`
- `ssh-keygen -t rsa -b 2048`
- launch `tmate` from your terminal
- once inside the tmate session, type `tmate show-messages`
- you can send ssh link, under my comment
- Once I connect, I interact with you on your terminal

Think of tmate as a TeamViewer for terminal only, no GUI.

**Comment by gaby** [comment]
@vaguileradiaz Any updates on this?

**Comment by ghost** [comment]
Don't bother
The author has abandoned the project since Apr. 2018, you can check the commit history.

As mentionned above, the only way to use Tinfoleak, is to download the exe version available in the source

**Comment by w70t** [comment]
> Hey, does the program still working?
What's your problem?

**Comment by Andrejki** [comment]
I can t be authenticated in configuration settings.  
Nevertheless, Whotwi online use - it s similar.

**Comment by dhupee** [comment]
> Whotwi online use - it s similar.

looks like it shutdown for another service mate
